/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2019-10-09 17:33:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class endsession64_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



   //Avaya Aura Contact Center Multimedia 
   //Copyright 2014 Avaya Inc. All Rights Reserved
   
   //Session close is already handled in exitFormImpl64.jsp
   

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <script type=\"text/javascript\"> \n");
      out.write("                    \n");
      out.write("                function onLoadDo()\n");
      out.write("                {\n");
      out.write("                        //\tOn window load resize\n");
      out.write("                        resizeWindow(438, 438, 438, 415, 433, 397, 0);\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                //\tResize pop-up according to browser used, and by possible extending length\n");
      out.write("                function resizeWindow(ffPixelWidth, crPixelWidth, iePixelWidth, ffPixelLength, crPixelLength, iePixelLength, extendLength)\n");
      out.write("                {\n");
      out.write("                        if (/Firefox[\\/\\s](\\d+\\.\\d+)/.test(navigator.userAgent))\n");
      out.write("                                window.resizeTo(ffPixelWidth, ffPixelLength + extendLength);\t//\tFirefox\n");
      out.write("                        else if(navigator.userAgent.indexOf(\"Chrome\") != -1)\n");
      out.write("                                window.resizeTo(crPixelWidth, crPixelLength + extendLength);\t//\tChrome\n");
      out.write("                        else if(navigator.appName == \"Microsoft Internet Explorer\")\n");
      out.write("                        {\n");
      out.write("                                extendLength -= extendLength/14;\n");
      out.write("                                window.resizeTo(iePixelWidth, iePixelLength + extendLength);\t//\tIE\n");
      out.write("                        }\n");
      out.write("                        else \n");
      out.write("                                window.resizeTo(iePixelWidth, iePixelLength + extendLength);\t//\tResize others as of IE\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                </script>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body onload=\"Javascript:onLoadDo()\" style=\"margin:0px;\">\n");
      out.write("            \n");
      out.write("            <table id=\"banner\" class=\"top_gradient\" width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("            \n");
      out.write("                <!--\tHeader & Logo\t-->\t\n");
      out.write("                <tr>\n");
      out.write("                        <td width=\"81\" style=\"padding-top:25px;padding-left:50px;\" align=\"right\" valign=\"top\" ><img alt=\"\" src=\"img/smallLogo.png\" /></td>\n");
      out.write("                        <td width=\"349\" style=\"padding-top:25px;padding-left:15px;\" align=\"left\" valign=\"top\"><img alt=\"\" src=\"img/chat.png\"/></td>\n");
      out.write("                        <td/> </td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <!-- Goodbye Message -->\n");
      out.write("                <tr height=\"200\">\n");
      out.write("                    <td colspan=\"3\" align=\"center\"><label align=\"center\" style=\"font-size:14.0pt;\">Thank you for visiting. Goodbye...</label></td>\n");
      out.write("                </tr>\n");
      out.write("               \n");
      out.write("            </table>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
