/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2019-10-22 17:05:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.nortel.applications.ccmm.ci.datatypes.*;
import com.nortel.applications.ccmm.ci.webservices.*;

public final class index64_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  public java.lang.String getServletInfo() {
    return "Chat";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<HTML>\n");
      out.write(" <HEAD>\n");
      out.write("    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\n");
      out.write("    <title>Seguros Atlas</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\n");
      out.write("    \n");
      out.write("    <script type=\"text/javascript\"> \n");
      out.write("    var elementID;\n");
      out.write("\n");
      out.write("    // Resize the window to account for advert area & webchat history\n");
      out.write("    function onLoadDo()\n");
      out.write("    {\n");
      out.write("            //\tOn window load resize\n");
      out.write("            resizeWindow(500, 500, 500, 692, 633, 606, 0);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    //\tResize pop-up according to browser used, and by possible extending length\n");
      out.write("    function resizeWindow(ffPixelWidth, crPixelWidth, iePixelWidth, ffPixelLength, crPixelLength, iePixelLength, extendLength)\n");
      out.write("    {\n");
      out.write("            if (/Firefox[\\/\\s](\\d+\\.\\d+)/.test(navigator.userAgent))\n");
      out.write("                    window.resizeTo(ffPixelWidth, ffPixelLength + extendLength);\t//\tFirefox\n");
      out.write("            else if(navigator.userAgent.indexOf(\"Chrome\") != -1)\n");
      out.write("                    window.resizeTo(crPixelWidth, crPixelLength + extendLength);\t//\tChrome\n");
      out.write("            else if(navigator.appName == \"Microsoft Internet Explorer\")\n");
      out.write("            {\n");
      out.write("                    extendLength -= extendLength/14;\n");
      out.write("                    window.resizeTo(iePixelWidth, iePixelLength + extendLength);\t//\tIE\n");
      out.write("            }\n");
      out.write("            else \n");
      out.write("                    window.resizeTo(iePixelWidth, iePixelLength + extendLength);\t//\tResize others as of IE\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // Called by chat frameset to close the chat window when the agent is finished\n");
      out.write("    function closeChatWindow()\n");
      out.write("    {\n");
      out.write("            //\tExit the chat window\n");
      out.write("            window.close();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    </script>        \n");
      out.write("        \n");
      out.write(" </HEAD>\n");
      out.write("   \n");
      out.write("  <FORM name=hiddenForm>\n");
      out.write("\n");


   //Avaya Aura Contact Center Multimedia 
   //Copyright � 2014 Avaya Inc. All Rights Reserved


	String 		sessionKey;
	String 		contactID;
        String          telnumber;

	String ccmmHostname  = application.getInitParameter("CCMM_HOSTNAME");

	request.setCharacterEncoding("utf-8");
	sessionKey=request.getParameter("sessionKey");
	contactID=request.getParameter("contactID");
        telnumber=request.getParameter("telnumber");

	// create the session based on passed in session and contact ID's
	try
   	{

		java.net.URL ciWebCommsWsUrl = new java.net.URL("http://" + ccmmHostname + "/ccmmwebservices/CIWebCommsWs.asmx"); 

		CIWebCommsWs webCommsWsLocator = new CIWebCommsWsLocator();
		CIWebCommsWsSoap webCommsWs = webCommsWsLocator.getCIWebCommsWsSoap( ciWebCommsWsUrl );

		long result = webCommsWs.createWebCommsSession(new Long(contactID).longValue(), sessionKey);    

	}
   	catch(Exception e)
   	{
	     // response.sendRedirect("closed.jsp"); 	
	}


      out.write("\n");
      out.write("\n");
      out.write(" <FRAMESET onload=\"Javascript:onLoadDo()\" ROWS=\"40%, 60%, 8%, 0%, 0%\" border=\"0\">\n");
      out.write("\n");
      out.write("        <FRAMESET COLS=\"100%,0%\" border=\"0\">\n");
      out.write("        \t<FRAME SRC=\"chatdisplay64.jsp?sessionKey=");
      out.print(sessionKey);
      out.write("&contactID=");
      out.print(contactID);
      out.write("\" name=\"chatdisplay\">\n");
      out.write("                <FRAME SRC=\"onhold64.jsp\" name=\"maincontrol\">\n");
      out.write("        </FRAMESET>\n");
      out.write(" \t<FRAMESET COLS=\"10%,90%\" border=\"0\">\n");
      out.write("\t\t<FRAME SRC=\"status64.jsp?sessionKey=");
      out.print(sessionKey);
      out.write("&contactID=");
      out.print(contactID);
      out.write("\" name=\"statuscontrol\" scrolling=none>\n");
      out.write("                    <FRAME SRC=\"chatwrite64.jsp?sessionKey=");
      out.print(sessionKey);
      out.write("&contactID=");
      out.print(contactID);
      out.write("&telnumber=");
      out.print(telnumber);
      out.write("\" name=\"chatwrite\">\n");
      out.write("\t</FRAMESET>\n");
      out.write("        <FRAME SRC=\"footer.jsp\" name=\"footer\">\n");
      out.write("\t<FRAME SRC=\"hidden64.jsp?sessionKey=");
      out.print(sessionKey);
      out.write("&contactID=");
      out.print(contactID);
      out.write("\" name=\"wcControl\"> <!-- Refreshes every 3 seconds to update chat history and agent messages -->\n");
      out.write("\t<FRAME SRC=\"heartbeat.jsp?sessionKey=");
      out.print(sessionKey);
      out.write("&contactID=");
      out.print(contactID);
      out.write("\" name=\"wcHeartbeat\"> <!-- Session heartbeat. Runs every 30 seconds -->\n");
      out.write("\n");
      out.write(" </FRAMESET>\n");
      out.write("\n");
      out.write(" </FORM>\n");
      out.write("       \n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
