/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2019-10-10 18:37:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class OfferWebChat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--\n");
      out.write("Avaya Aura Contact Center Multimedia \n");
      out.write("Copyright © 2014 Avaya Inc. All Rights Reserved\n");
      out.write("-->\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\n");
      out.write("        <title>Web Chat Offer Sample</title>\n");
      out.write("    </head>\n");
      out.write("    <body onload=\"Javascript:showQuestionWin()\">\n");
      out.write("\n");
      out.write("        <table id=\"winDisplay\" class=\"popover_window_confirm\" style=\"display:none;\" cellSpacing=\"0\" cellPadding=\"0\" border=\"0\">\n");
      out.write("            <tr>\n");
      out.write("                    <td>   \n");
      out.write("                    <table id=\"\" cellSpacing=\"0\" cellPadding=\"0\" border=\"0\" class=\"top_gradient\">  \n");
      out.write("\n");
      out.write("                            <!-- Header --> \n");
      out.write("                            <tr height=\"70\">\n");
      out.write("                                <td width=\"81\" style=\"padding-top:25px;padding-left:50px;\" align=\"right\" valign=\"top\" ><img alt=\"\" src=\"img/smallLogo.png\" /></td>\n");
      out.write("                                <td width=\"349\" style=\"padding-top:25px;padding-left:15px;\" align=\"left\" valign=\"top\"><img alt=\"\" src=\"img/chat.png\"/></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <!-- End Header --> \n");
      out.write("\n");
      out.write("                            <!-- Question --> \n");
      out.write("                            <tr>\n");
      out.write("                                    <td rowspan=\"2\" style=\"padding-left:20;\" ><img src=\"img/avaya_agent.png\" border=\"0\" class=\"webchat_agent_image\"></td>\n");
      out.write("                                    <td style=\"padding-top:30;padding-left:30;\">Would you like to chat with an agent?</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                                    <td style=\"padding-top:20; padding-bottom:20;\" align=\"middle\"><INPUT TYPE=\"submit\"onClick=\"LoadAgent()\" value=\"Yes\"> <INPUT TYPE=\"submit\"onClick=\"closeQuestionWin()\" value=\"No\"></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <!-- End Question --> \n");
      out.write("\n");
      out.write("                    </table>\n");
      out.write("                    </td>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("            <!-- Footer -->\n");
      out.write("            <tr height=\"50\">\n");
      out.write("                    <td class=\"bottom_gradient\" width=\"100%\">\n");
      out.write("                            <div>\n");
      out.write("                                    <span class=\"powered_by\">Powered by Avaya Aura Contact Center</span>\n");
      out.write("                            </div>\n");
      out.write("                    </td>\n");
      out.write("            </tr>\n");
      out.write("            <!-- End Footer -->\n");
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function showQuestionWin() \n");
      out.write("{ \n");
      out.write("\tdocument.getElementById('winDisplay').style.display = \"\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("function closeQuestionWin() \n");
      out.write("{  \n");
      out.write("\twindow.close();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function LoadAgent()\n");
      out.write("{\n");
      out.write("    window.open('WebChatLogin.jsp', 'WebChat', 'width=430, height=400, resizable=0')\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>        \n");
      out.write("        \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
