/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2019-10-24 16:21:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class WebChatLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\n");
      out.write("\t\t<title>Sample Web Chat</title>\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/calendar.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/time.css\" />\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body onload=\"Javascript:onLoginLoadDo()\" style=\"margin:0px;\" bgcolor=\"#F3F2EF\">\n");
      out.write("\t\t<div>escribenos</div>\n");
      out.write("            \n");
      out.write("            <form name=\"requestWebChatform\"  onsubmit=\"return processChatRequest()\" method=\"POST\" action=\"RequestWebChat_Redirect.jsp\">\n");
      out.write("\n");
      out.write("\t\t<table id=\"webchatLogin\" class=\"popover_window\" width=\"430\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td width=\"100%\">\n");
      out.write("\t\t\t\t\t<table id=\"\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">  \n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!--\tHeader & Logo\t-->\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!--\tEnd Header & Logo\t-->\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" valign=\"top\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Input Fields -->\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"\" cellSpacing=\"0\" cellPadding=\"0\" border=\"0\" width=\"100%\">  \n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table id=\"webchat_user_input\" class=\"input_fields\" width=\"100%\" valign=\"top\"  style=\"display:block;\" border=\"0\" cellSpacing=\"3\" cellPadding=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"110\">Nombre</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"field\" maxlength=\"50\" id=\"username\" name=\"username\" size=\"30\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"name_error\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"110\">Telefono:</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"field\" maxlength=\"50\" id=\"phone\" name=\"phone\" size=\"30\" onKeyPress=\"return checkSpace(event)\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"phone_error\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"110\">Correo Electronico:</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"field\" maxlength=\"50\" id=\"email\" name=\"email\" size=\"30\" onKeyPress=\"return checkSpace(event)\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"email_error\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><input hidden type=\"field\" maxlength=\"50\" id=\"subject\" name=\"subject\" size=\"30\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"subject_error\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><input hidden type=\"field\" maxlength=\"50\" id=\"reference\" name=\"reference\" size=\"30\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td id=\"reference_error\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr align=\"left\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select hidden style=\"width:205px;\" id=\"skillset\" name=\"skillset\">\n");
      out.write("        \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"WC_Default_Skillset\">Default</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!-- End Input Fields -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Please Wait / Error Message Table -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"webchat_please_wait\" valign=\"top\" class=\"input_fields\" style=\"display:none;\" width=\"100%\" border=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td id=\"PleaseWait\" height=\"152\" width=\"438\" valign=\"middle\" align=\"center\">Favor de esperar...</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t</table> \n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!-- End Please Wait / Error Message Table -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" style=\"padding:20px;\" colspan =\"2\"> \n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"wc_submit\" value=\"Iniciar Chat\"/>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Footer -->\n");
      out.write("\n");
      out.write("\t\t\t\t<td colspan=\"2\" class=\"bottom_gradient\" height=\"50\" width=\"100%\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<span id=\"status\" class=\"webchat_connection_status\"><b><font class=\"status_color\">Status: </font>Activo</b></span>\n");
      out.write("\t\t\t\t\t<span class=\"powered_by\">Seguros Atlas</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- End Footer -->\n");
      out.write("\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/main_pre_body.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\"> \n");
      out.write("var elementID;\n");
      out.write("\n");
      out.write("function onLoginLoadDo()\n");
      out.write("{\n");
      out.write("\t//\tOn window load resize\n");
      out.write("\tresizeWindow(438, 438, 438, 415, 433, 397, 0);\n");
      out.write("\n");
      out.write("\t//\tSet focus to name field\n");
      out.write("\tdocument.getElementById('username').focus();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function replaceWithHTMLEntities(str)\n");
      out.write("{\n");
      out.write("\t//\tReplace certain 'vulnerable' characters with their html entities\n");
      out.write("\tstr = str.replace(\"<\", \"&#60;\");\n");
      out.write("\tstr = str.replace(\">\", \"&#62;\");\n");
      out.write("\tstr = str.replace(\"$\", \"&#36;\");\n");
      out.write("\tstr = str.replace(\"[\", \"&#91;\");\n");
      out.write("\tstr = str.replace(\"[\", \"&#93;\");\n");
      out.write("\treturn str; \n");
      out.write("}\n");
      out.write("\n");
      out.write("function processChatRequest()\n");
      out.write("{\n");
      out.write("\n");
      out.write("    \tvar error = false;\n");
      out.write("\telementID = 0;\n");
      out.write("\n");
      out.write("\t//\tGet input\n");
      out.write("\tvar username = replaceWithHTMLEntities(document.getElementById('username').value);\n");
      out.write("\tvar email = replaceWithHTMLEntities(document.getElementById('email').value);\n");
      out.write("\tvar phone = replaceWithHTMLEntities(document.getElementById('phone').value);\n");
      out.write("\n");
      out.write("\t//\tRetrieve platform and browser information to pass to agent\n");
      out.write("\tvar WebCommsQuery = \"PLATFORM: [\" + navigator.platform + \"]; BROWSER: [\" + navigator.appName + \"]; HEADER: [\" + navigator.userAgent + \"]\";\n");
      out.write("\n");
      out.write("\t//\tAssign username to first name for creating user in database\n");
      out.write("\tFirstName = username;\n");
      out.write("\n");
      out.write("\tdocument.getElementById('email_error').innerHTML = \"\";\n");
      out.write("\tdocument.getElementById('phone_error').innerHTML = \"\";\n");
      out.write("  \n");
      out.write("\t//\tValidate given email address\n");
      out.write("\tif(email != \"\")\n");
      out.write("\t{\n");
      out.write("\t\t//\tIf string contains whitespace, trim\n");
      out.write("\t\temail = whitespaceTrim(email);\n");
      out.write("\t\t//\t Validate email address\n");
      out.write("\t\tif(!isValidEmailAddress(email))\n");
      out.write("\t\t{\n");
      out.write("\t\t\tdocument.getElementById('email_error').innerHTML = \"<font color='red'>Invalid Email Address</font>\";\n");
      out.write("\t\t\terror = true;\n");
      out.write("\t\t\telementID = document.getElementById('email');\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t//\tValidate given phone number\n");
      out.write("\tif(phone != \"\")\n");
      out.write("\t{\n");
      out.write("\t\t//\tIf string contains whitespace, trim\n");
      out.write("\t\tphone = whitespaceTrim(phone);\n");
      out.write("\t\t//\t Validate phone number\n");
      out.write("\t\tif(!isValidPhoneNumber(phone))\n");
      out.write("\t\t{\n");
      out.write("\t\t\tdocument.getElementById('phone_error').innerHTML = \"<font color='red'>Invalid Phone Number</font>\";\n");
      out.write("\t\t\terror = true;\n");
      out.write("\t\t\tif (elementID == 0)\n");
      out.write("\t\t\t\telementID = document.getElementById('phone');\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t// Check for error\n");
      out.write("\tif(error)\n");
      out.write("\t{\n");
      out.write("\t\t//\tSet element focus\n");
      out.write("\t\telementID.focus();\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t//\tHide user input panel\n");
      out.write("\tdocument.getElementById('webchat_user_input').style.display = \"none\";\n");
      out.write("\n");
      out.write("\t//\tShow loading panel while we do all the web service calls and it can take a few seconds to complete\n");
      out.write("\tdocument.getElementById('webchat_please_wait').style.display = \"block\";\n");
      out.write("\n");
      out.write("\t//\tMaintain window size (according to browser used) while wait message is displayed and the chat request is processed\n");
      out.write("\tresizeWindow(438, 438, 438, 415, 408, 381, 0);\n");
      out.write("        \n");
      out.write("\treturn true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("            </form>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
